### ISSUE TITLE
how to update "model.pickle.dat"

### ISSUE THREAD

**Issue by marrrs88** [tsakurai42/dota2-win-prediction#1]
Hello bro.
I am a new guy here and I am very interested in your project and tried to using it.
But it seems that there is no codes here could update this "model.pickle.dat"file.
Could you please guide me for this.
Thanks a lot.

**Comment by cherryfox42** [comment]
So this was mostly made for me to test and learn how to use ML. If you want to work on different parameters for the model, it was created within the Jupyter notebook. There's some commenting and instructions in it, but it's unfortunately not set up for ease of use at the moment.

**Comment by marrrs88** [comment]
Thanks a lot for your patient response.

**Comment by cherryfox42** [comment]
Of course. For what it's worth, I need to double check, but I'm not sure how well my model would have predicted TI9. OG would have thrown everything off.
